version: '3'
services:
  app: # railsコンテナの定義
    build: . # dockerファイルを基に、イメージ作成
    command: bundle exec rails s -p 3000 -b '0.0.0.0' # コンテナ起動時にデフォルトで入力されるコマンドを設定している。
    # この文は、railsサーバーを、「localhost:3000」で起動するコマンド。-pでポート番号、-bでバインドするIPアドレス
    volumes:
      - .:/app # よう分からんけどこれすれば、PCで変更した内容が即座にコンテナに反映される
    ports:
      - 3000:3000 #[公開するポート番号]:[コンテナ内部の転送先ポート番号]
    depends_on:
      - db # 「dbに依存」なので、mysqlサーバーが先に起動してから、これが起動する
    tty: true
    stdin_open: true #この２つ無いと、pry使えへん。
  db: # mysqlサーバーコンテナの定義
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume:

